services:
  backend:
    build: ./pokedex-backend
    container_name: pokedex-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SUPABASE_URL=https://pergcqdvwbasvtkranfd.supabase.co
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcmdjcWR2d2Jhc3Z0a3JhbmZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTY0NDQzNCwiZXhwIjoyMDk1MjIwNDM0fQ.G2gNK1YNctvAFsOyxVRDmEyOBOCOHxVlCJomnYJEstI
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcmdjcWR2d2Jhc3Z0a3JhbmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2NDQ0MzQsImV4cCI6MjA5NTIyMDQzNH0.HYI_qMVjCl5UmbXfrNIoiMNIGB1B_m-VKQ7YJ-OcoMg
      - SERVER_URL=http://localhost:3000
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
