sonar.projectKey=pokedex-backend
sonar.projectName=Pokedex Backend
sonar.projectVersion=1.0
sonar.sources=src,index.js
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,openapi.json
sonar.javascript.lcov.reportPaths=