sonar.projectKey=anime-backend
sonar.projectName=AnimeApp Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=node_modules/**,**/*.test.js
sonar.host.url=http://localhost:9000
sonar.token=PENDIENTE
